[package]
name = "oci-support"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
execution-proto = { path = "../execution-proto", version = "=0.1.0" }
guest-image = { path = "../guest-image", version = "=0.1.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tempfile = "3"
thiserror = "2"

[lints]
workspace = true
