# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "m6-rust-lost-update"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[workspace]

[dependencies]
hypercall-proto = { path = "../../../hypercall-proto", version = "0.1.0", default-features = false, features = ["guest"] }
