[package]
name = "workload-tools"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[workspace]

[dependencies]
consonance-client = { version = "=0.1.0", path = "../../consonance/client", features = ["in-process"] }
control-proto = { version = "=0.1.0", path = "../../consonance/control-proto" }
nes-workload = { path = "../nes", version = "=0.1.0" }
