// SPDX-License-Identifier: AGPL-3.0-or-later
#![no_std]

mod device;
mod error;
mod state;

pub use device::{Lapic, LapicConfig};
pub use error::LapicError;
pub use state::{
    APIC_BASE_DEFAULT, APIC_DFR, APIC_EOI, APIC_ESR, APIC_ICR_HIGH, APIC_ICR_LOW, APIC_ID,
    APIC_IRR, APIC_ISR, APIC_LDR, APIC_LVT_ERROR, APIC_LVT_LINT0, APIC_LVT_LINT1, APIC_LVT_PERFMON,
    APIC_LVT_THERMAL, APIC_LVT_TIMER, APIC_MAX_OFFSET, APIC_MMIO_SIZE, APIC_PPR, APIC_SVR,
    APIC_TDCR, APIC_TMCCT, APIC_TMICT, APIC_TMR, APIC_TPR, APIC_VERSION, APIC_VERSION_VALUE,
    LAPIC_STATE_VERSION, LapicState,
};
